### ISSUE TITLE
ChatBedrockConverse doesn't take into account boto3 setup_default_session.

### ISSUE THREAD

**Issue by thiagotps** [langchain-ai/langchain-aws#157]
The following code:
```python
import boto3
from langchain_aws import ChatBedrockConverse

boto3.setup_default_session(profile_name="genai-dev", region_name="us-east-1")
llm = ChatBedrockConverse(model="anthropic.claude-3-haiku-20240307-v1:0")
```
raises the following error:
```python
ValidationError: 1 validation error for ChatBedrockConverse
__root__
  Did not find region_name, please add an environment variable `AWS_DEFAULT_REGION` which contains it, or pass `region_name` as a named parameter. (type=value_error)
```
The error is asking for the environmental variable `AWS_DEFAULT_REGION`, even though I have set the region name via boto3 `setup_default_session` method.

**Comment by isahers1** [comment]
I believe you need to pass `region_name` directly into `ChatBedrockConverse` - or set the environment variable `AWS_DEFAULT_REGION`. boto3 and langchain_aws don't share variables, so you must specify the region name for the llm as well I believe. Let me know if that fixes your error.

**Comment by isahers1** [comment]
Not a `boto3` expert by any means - but if I understand correctly the code currently creates its own session, but you would like it to work with the session already setup? That sounds reasonable to me - if you want to open up a PR (with a corresponding test case) I would be happy to review. Lmk if I misunderstood

**Comment by 3coins** [comment]
@thiagotps 
I believe this has been fixed in the latest release. I am not able to reproduce with v0.2.2. Let us know if you still see this issue.

**Comment by Sheile** [comment]
@3coins 
I've reproduce this issue in langchain-aws 0.2.31 if `~/.aws/config` does not exists.

### reproduce.py
```python
import boto3
from langchain_aws import ChatBedrockConverse

boto3.setup_default_session(region_name="ap-northeast-1")

print("--- Specify region_name directly")
llm1 = ChatBedrockConverse(model="anthropic.claude-3-5-sonnet-20240620-v1:0", region_name="ap-northeast-1")
answer1 = llm1.invoke("hello")
print(answer1.content)

print()
print("--- Don't specify region_name directly")
llm2 = ChatBedrockConverse(model="anthropic.claude-3-5-sonnet-20240620-v1:0")
answer2 = llm2.invoke("hello")
print(answer2.content)
```

### Teminal commands
```bash
bash-5.2# ls ~/.aws
ls: cannot access '/root/.aws': No such file or directory

bash-5.2# env | grep AWS_DEFAULT_REGION    # Does not exist

bash-5.2# pip freeze | grep langchain-aws
langchain-aws==0.2.31
bash-5.2# pip freeze | grep langchain-core
langchain-core==0.3.76

bash-5.2# export AWS_ACCESS_KEY_ID=AKIA*****
bash-5.2# export AWS_SECRET_ACCESS_KEY=*****
bash-5.2# python reproduce.py
--- Specify region_name directly
Hello! How can I assist you today? Feel free to ask me any questions or let me know if there's anything you'd like help with.

--- Don't specify region_name directly
Traceback (most recent call last):
  File "/tmp/reproduce.py", line 13, in <module>
    llm2 = ChatBedrockConverse(model="anthropic.claude-3-5-sonnet-20240620-v1:0")
  File "/usr/local/lib/python3.13/site-packages/langchain_core/load/serializable.py", line 115, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ChatBedrockConverse
  Value error, Could not load credentials to authenticate with AWS client. Please check that the specified profile name and/or its credentials are valid. Service error: You must specify a region. [type=value_error, input_value={'model': 'anthropic.clau...sable_streaming': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/value_error
```
