### ISSUE TITLE
`ChatBedrockConverse` and `with_structured_output` not working with `claude-3-sonnet`

### ISSUE THREAD

**Issue by ninedigits** [langchain-ai/langchain-aws#183]
Worked with previous version `Version: 0.1.9`
No longer works with current version `Version: 0.1.17`

Code: 
```python3
class ContractMetaData(BaseModel):
    """...
    """
    
    start_year: Optional[str] = Field(
        default=None, description="""
        The year when the contract first became active.
        """
    )
    ...

model_id = "anthropic.claude-3-sonnet-20240229-v1:0"
llm = ChatBedrockConverse(
    model_id=model_id,
)
prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are an expert extraction algorithm. "
            "Only extract relevant information from the text. "
            "If you do not know the value of an attribute asked to extract, "
            "return null for the attribute's value. "
            "Keep answers concise, and opt for as few words as possible."
            ,
        ),
        # Please see the how-to about improving performance with
        # reference examples.
        # MessagesPlaceholder('examples'),
        ("human", "{text}"),
    ]
)

runnable = prompt | llm.with_structured_output(ContractMetaData)
runnable.invoke({"text": contract_text_data})
```
Produces the following error:
```shell
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/all_repos/LLMs/contract_manufacturing/src/main_extract_contracts.py", line 27, in <module>
    extractor = ContractExtractor()
  File "/home/ec2-user/SageMaker/all_repos/LLMs/contract_manufacturing/src/model.py", line 138, in __init__
    self.chain = self._create_extraction_chain()
  File "/home/ec2-user/SageMaker/all_repos/LLMs/contract_manufacturing/src/model.py", line 142, in _create_extraction_chain
    llm = ChatBedrockConverse(
  File "/home/ec2-user/anaconda3/envs/extractor_env/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 113, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/extractor_env/lib/python3.10/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/home/ec2-user/anaconda3/envs/extractor_env/lib/python3.10/site-packages/pydantic/v1/main.py", line 1048, in validate_model
    input_data = validator(cls_, input_data)
  File "/home/ec2-user/anaconda3/envs/extractor_env/lib/python3.10/site-packages/langchain_aws/chat_models/bedrock_converse.py", line 365, in set_disable_streaming
    or (values.get("model_id", values["model"])).split(".")[0]
KeyError: 'model'
```

**Comment by ninedigits** [comment]
I figured it out. The problem is that the parameter `model_id` is now `model`

Changing:
```python3
model_id = "anthropic.claude-3-sonnet-20240229-v1:0"
llm = ChatBedrockConverse(
    model_id=model_id,
)
```
To
```python3
model_id = "anthropic.claude-3-sonnet-20240229-v1:0"
llm = ChatBedrockConverse(
    model=model_id,
)
```
Solved the problem.
