### ISSUE TITLE
Regression after upgrading to langchain-aws==0.1.17

### ISSUE THREAD

**Issue by shrikrishnaholla** [langchain-ai/langchain-aws#185]
### Versions of dependencies
```
langchain-aws==0.1.17
boto3==1.34.155
botocore==1.34.155
langchain-community==0.2.0
langchain-core==0.2.37
langchain==0.2.0
```

### Code snippet
My code looks like this (only partial code is reproduced here for brevity)

```python
import boto3
import boto3.session
from os import getenv
from langchain.chains import RetrievalQA
from langchain_aws.llms.bedrock import BedrockLLM

session = boto3.session.Session(
    aws_access_key_id=getenv("S3_ACCESSKEY"),
    aws_secret_access_key=getenv("S3_SECRETKEY"),
    region_name=getenv("S3_REGION"),
)

bedrock_client = session.client("bedrock-runtime")

AWS_BEDROCK_REGION = getenv("AWS_BEDROCK_REGION")

llm = BedrockLLM(
        model_id=kwargs.get("model_kwargs", {}).get("model", MODEL__MIXTRAL_8X7B),
        model_kwargs=kwargs.get("model_kwargs", {"temperature": 0}),
        client=bedrock_client,
        region_name=AWS_BEDROCK_REGION,
        callbacks=kwargs.get("model_callbacks"),
)

qa = RetrievalQA.from_chain_type(
        llm=llm,
        ...other params
)

answer = qa.invoke({"query": query})
```

### Error thrown
```python
An error occurred (ValidationException) when calling the InvokeModel operation: Validation Error
ERROR:flask.app:Exception on /api/v1 [POST]
Traceback (most recent call last):
  File "/home/core/.local/lib/python3.8/site-packages/langchain_aws/llms/bedrock.py", line 715, in _prepare_input_and_invoke
    response = self.client.invoke_model(**request_options)
  File "/home/core/.local/lib/python3.8/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/core/.local/lib/python3.8/site-packages/botocore/client.py", line 1017, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: Validation Error
```

There is no information made available as to the actual validation that failed, so I'm kinda stuck here. What am I missing?

**Comment by shrikrishnaholla** [comment]
So I logged the error response from API in botocore, and I got this:

```
{'headers': {'Date': 'Sat, 07 Sep 2024 08:07:20 GMT', 'Content-Type': 'application/json', 'Content-Length': '30', 'Connection': 'keep-alive', 'x-amzn-RequestId': 'f369a4ed-cbb9-4f5c-bae8-e0fbe839a513', 'x-amzn-ErrorType': 'ValidationException:http://internal.amazon.com/coral/com.amazon.bedrock/'}, 'status_code': 400, 'context': {'operation_name': 'InvokeModel'}, 'body': b'{"message":"Validation Error"}'}
```

It seems like there is some bug in one of the parameters passed to a bedrock api? But still no clarity on what that is because of overly generic error message. Anyone from AWS here who could help?

**Comment by shrikrishnaholla** [comment]
Ok, I figured it out. The extra key "model" in `model_kwargs` was causing the validation to fail. Maybe error messages could be improved? Is the validation performed at the layer of langchain-aws, or boto3 or botocore? If someone is willing to guide, would be happy to contribute. 

In any case, since my issue is resolved, I'm closing this
